### ISSUE TITLE
Debian8 in Esxi failed

### ISSUE THREAD

**Issue by lowprofileusername** [outime/ipv6-dhclient-script#5]
WARNING: Network will restart at the end of this script so any existing connections will be dropped!
Interface where IPv6 will be enabled: eth0
You have the following IPv6 addreses configured for eth0:
fe80::250:56ff:fe00:ef29
Continue? [Y/n]: Y
Your IPv6 block address (e.g. 2001:bb8:3e23:200::): 2001:0xcx:xxxx::
Subnet for your block (e.g. if it's /56, input 56): 48
Associated DUID (e.g. 00:03:00:00:34:b0:0c:47:4a:0e): 00:03:0x:01:7axx:96:xx:xx:xx
Working...
net.ipv6.conf.eth0.autoconf = 0
SIOCDELRT: No such process
SIOCDELRT: No such process
Failed to bring up eth0.
Testing IPv6 connectivity...
connect: Network is unreachable
Something went wrong :(

Same script worked for my ubuntu 14.04 and centos 6 under ESXI

I need help with debian 8

**Comment by lowprofileusername** [comment]
WARNING: Network will restart at the end of this script so any existing connections will be dropped!
Interface where IPv6 will be enabled: ens32
You have the following IPv6 addreses configured for ens32:
fe80::250:56ff:fe00:ef29
Continue? [Y/n]: Y
Your IPv6 block address (e.g. 2001:bb8:3e23:200::): 2xx0x:0bc8:x525::
Subnet for your block (e.g. if it's /56, input 56): 48
Associated DUID (e.g. 00:03:00:00:34:b0:0c:47:4a:0e): 00:03:00:01:7a:3e:96:ea:xx3d
Working...
net.ipv6.conf.ens32.autoconf = 0
SIOCDELRT: No such process
SIOCDELRT: No such process
RTNETLINK answers: Cannot assign requested address
Failed to bring up ens32.
Testing IPv6 connectivity...
connect: Network is unreachable
Something went wrong :(

same for ubuntu 16

**Comment by outime** [comment]
I tested the script last week (see LowEndTalk thread linked in the README) in both Debian 8 and Ubuntu 16.04 with a kidéchiré (Online.net) and a /56 subnet and worked like a charm. I don't want to say the "it works for me" but... :)

Since running the same tests in my account would yield the same outcome (and I don't have the server available for this purpose), I suggest that if you feel like it and want to contribute, you could reinstall Debian 8 or Ubuntu 16.04 and send me both the ssh credentials and ipv6 data to outime@gmail.com and I'd take a look during this weekend. I'd also understand if you wouldn't like to do that, but then troubleshooting will get more difficult.

**Comment by lowprofileusername** [comment]
I've sent you a email for detail. hope that would help.

**Comment by outime** [comment]
Ah right, so you're running these under a hypervisor. Which one is that? You might need to run the script in the host if supported (with ipv6 forwarding enabled) and then route addresses to the VMs.

**Comment by outime** [comment]
Sorry I completely overlooked the fact that you were running it under ESXi, then it's understandable that it doesn't work. You might need to run the script in the host if supported (with ipv6 forwarding enabled) and then route addresses to the VMs.
